
import numpy as np
import pandas as pd

from pygnss import filter
from pygnss.filter import particle, models

from pnt_datasets import ipin

def test__particle_filter():

    data_bundle = ipin.get_data(ipin.Dataset.IPIN_2023_T8, 'D5')

    n_particles = 100

    particles = _first_particles_from_nodes(data_bundle.nodes, n_particles)
    weight_estimator = particle.WeightEstimatorGaussian
    model = models.RangePositioning2D(np.eye(2), data_bundle.nodes)
    state_handler = StateHandler()

    pfilter = particle.Filter(particles,
                        weight_estimator,
                        model,
                        state_handler)
    n_particles = 100

    particles = _first_particles_from_nodes(data_bundle.nodes, n_particles)

    pfilter = particle.Filter(particles,
                              weight_estimator,
                              model,
                              state_handler)

    for tstamp, measurements in data_bundle.measurements.groupby(ipin.TIMESTAMP_STR):

        y_k = measurements[ipin.TOA_STR].to_numpy() * 1.0e-9 * 299792458.0

        r_error = 1/ np.power(10, (measurements[ipin.RSRP_STR].to_numpy() - 30) / 10) / 1e8  # To linear and then scaling
        R = np.diag(r_error)

        pfilter.process(y_k, R, timestamp=tstamp)

        break


class StateHandler(filter.StateHandler):
    """
    Abstract class that handles the state generated by UKF
    """

    def __init__(self):
        pass

    def process_state(self, state: np.array, _covariance_matrix: np.array, **kwargs):
        """
        Process the state and associated covariance_matrix
        """

        print(state)


def _first_particles_from_nodes(nodes: pd.DataFrame, n_particles: int) -> np.array:

    coordinates = nodes[[ipin.X_STR, ipin.Y_STR]]

    min_x, min_y = np.min(coordinates, axis=0)
    max_x, max_y = np.max(coordinates, axis=0)
    dx = (max_x - min_x) / 2.0
    dy = (max_y - min_y) / 2.0

    particles = np.random.uniform((min_x - dx, min_y-dy), (max_x+dx, max_y+dy), (n_particles, 2))

    return particles


