from abc import ABC, abstractmethod
import copy
from dataclasses import dataclass
import logging
from typing import Callable, List
import numpy as np

from . import Model, State, StateHandler, FilterInterface


@dataclass
class Particles:
    particles: List[State]
    weights: List[float]

    def get_max_likely(self) -> State:
        """Get the particle with higher weight"""

        return self.particles[np.argmax(self.weights)]

    def __len__(self) -> int:
        """Get the number of particles"""

        return len(self.particles)

ResampleCallbackSignature = Callable[[Particles, int], Particles]

def resample(particles:Particles, new_n_particles:int = 100) -> Particles:

    cumulative_distribution = np.cumsum(particles.weights)

    q = np.sort(np.random.uniform(size=new_n_particles))

    particle_indices = [np.argwhere(cumulative_distribution > th)[0][0] for th in q]

    new_particles = [copy.deepcopy(particles[i]) for i in particle_indices]
    new_weights = np.array([1/new_n_particles] * new_n_particles)

    return Particles(new_particles, new_weights)

class WeightEstimatorInterface(ABC):
    """
    Interface for the object required to compute the weight
    of a particle
    """

    @abstractmethod
    def compute(self, prefits:np.array, **kwargs) -> float:
        """
        Compute the weights

        :param prefits: List of differences between the measurements and modelled measurements (based on the candidate particle/state)
        """


class WeightEstimatorGaussian(WeightEstimatorInterface):
    """
    Computes the weights of the prefits based on the likelihoods from a Gaussian distribution
    """

    def __init__(self):
        pass

    def compute(self, prefits:np.array, **kwargs) -> float:
        """
        Compute the weights

        :param prefits: List of differences between the measurements and modelled measurements (based on the candidate particle/state)

        :return: The weight, as likelihood
        :rtype: float

        The function implements this function

        .. math::
            w = \\prod_{i=1}^{N} \\frac{1}{\\sigma \\sqrt{2 \\pi}} e^{-\\frac{1}{2} \\left( \\frac{x_i - \\mu}{\\sigma} \\right)^2}

        where x are the prefits and
        where:
        * :math:`x_i` is the prefit for the i-th measurement
        * :math:`N` is the total number of measurements
        * :math:`\\mu` and :math:`\\sigma` are the mean and the standard deviation of the prefits.

        """

        bias = np.average(prefits)  # Rough estimation of the hardware bias to remove it from the neasurements
        std = np.std(prefits)

        likelihoods = gaussian(prefits, std, bias)

        weight = np.prod(likelihoods)

        return weight

class Filter(FilterInterface):

    def __init__(self,
                 initial_states: List[State],
                 weight_estimator: WeightEstimatorInterface,
                 model: Model,
                 state_handler: StateHandler,
                 resample_fn: ResampleCallbackSignature = resample,
                 logger: logging.Logger = logging):
        """
        Create a Particle Filter instance

        :param x: Initial set of states
        :param weight_estimator: Class in charge of computing the weights for each particle/state
        :param model: Model to propagate the state and compute the observations based on the state
        :param state_handler: Class that handles the output generated by the filter
        :param resample_fn: Method to resample the particles
        :param logger: Logging engine
        """

        self.particles = initial_states

        self.weight_estimator = weight_estimator
        self.model = model
        self.state_handler = state_handler
        self.resample = resample_fn
        self.logger = logger

        # Initial set of weights for the particles. Assuming equally weighted
        n_particles = len(self.particles)
        self.weights = np.array([1.0 / n_particles] * n_particles)


    def process(self, y_k: np.array, _R: np.array, **kwargs):
        """
        Process an observation batch
        """

        # Time update ----------------------------------------------------------
        particles = [self.model.propagate_state(particle) for particle in self.particles]

        for i, particle in enumerate(particles):
            prefits = y_k - self.model.to_observations(particle).y_m
            self.weights[i] = self.weight_estimator.compute(prefits, **kwargs)

        # Normalize the weights
        self.weights = self.weights / sum(self.weights)

        if self.state_handler:
            pass

        self.particles, self.weights = self.resample(self.particles, self.weights, len(self.particles))

        # Compute postfit residuals
        x = self._get_solution()

        r = y_k - self.model.to_observations(x, **kwargs).y_m

        self.state_handler.process_state(x, np.eye(len(x)), postfits=r, **kwargs)

    def _get_solution(self) -> State:

        return self.particles[np.argmax(self.weights)]

        # Take the median of the 6 largest weights
        arr1inds = self.weights.argsort()
        #sorted_particles = self.particles[arr1inds[::-1]]

        return self.particles[arr1inds[-3]]


def gaussian(x, mu, sigma):
    """
    Evaluates a Gaussian function (normal distribution).

    :param x: The input value(s) (scalar or NumPy array).
    :type x: float or numpy.ndarray
    :param mu: The mean (center) of the Gaussian.
    :type mu: float
    :param sigma: The standard deviation (width) of the Gaussian.
    :type sigma: float
    :return: The value(s) of the Gaussian function at x.
    :rtype: float or numpy.ndarray

    Example
    -------
    >>> import numpy as np
    >>> mean = 0
    >>> std_dev = 1
    >>> x_values = np.linspace(-3, 3, 100)
    >>> y_values = gaussian(x_values, mean, std_dev)
    >>> print(y_values[0:5])
    [0.00443185 0.00530579 0.00632878 0.00752133 0.00890582]
    """
    return (1.0 / (sigma * np.sqrt(2 * np.pi))) * np.exp(-0.5 * ((x - mu) / sigma) ** 2)
